name: 'starlite-action-alpha'
description: 'Integrates with Starlite (alpha)'
branding:
  icon: 'star'
  color: 'blue'
inputs:
  api-key:
    description: 'Starlite API key'
    required: true
  org-id:
    description: 'Organization ID'
    required: false
  record-id:
    description: 'Record ID'
    required: false
  skip-catalog:
    description: 'Skip updating the record (manifest file)?'
    required: false
    default: 'false'
  skip-standards:
    description: 'Skip updating the standards?'
    required: false
    default: 'false'
  skip-deployment:
    description: 'Skip running the deployment script?'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Run catalog script
      if: ${{ inputs.skip-catalog == 'false' }}
      run: ${{ github.action_path }}/bash starlite-action.sh --org-id ${{ inputs.org-id }} --record-id ${{ inputs.record-id }} --token ${{ inputs.api-key }} --action "catalog"
      shell: bash

    - name: Run standards script
      if: ${{ inputs.skip-standards == 'false' }}
      run: ${{ github.action_path }}/bash starlite-action.sh --org-id ${{ inputs.org-id }} --record-id ${{ inputs.record-id }} --token ${{ inputs.api-key }} --action "standards"
      shell: bash

    - name: Run deployment script
      if: ${{ inputs.skip-deployment == 'false' }}
      run: ${{ github.action_path }}/bash starlite-action.sh --org-id ${{ inputs.org-id }} --record-id ${{ inputs.record-id }} --token ${{ inputs.api-key }} --action "deployment"
      shell: bash